---
- name: WebQube Profile
  hosts: localhost
  become: true
  tasks:
    - name: Setup
      ansible.builtin.include_tasks: tasks/provision-setup.yml

    - name: Provision Certs
      ansible.builtin.include_tasks: tasks/provision-certs.yml

    - name: Provision Chrome
      ansible.builtin.include_tasks: tasks/provision-chrome.yml

    - name: Cleanup
      ansible.builtin.include_tasks: tasks/provision-cleanup.yml
