---
- name: ProtoQube Profile
  hosts: localhost
  become: true
  tasks:
    - name: Setup
      ansible.builtin.include_tasks: tasks/provision-setup.yml

    - name: Common
      ansible.builtin.include_tasks: tasks/provision-common.yml

    - name: Provision Security
      ansible.builtin.include_tasks: tasks/provision-security.yml

    - name: Provision DevTools
      ansible.builtin.include_tasks: tasks/provision-devtools.yml

    - name: Provision AVRTools
      ansible.builtin.include_tasks: tasks/provision-avrtools.yml

    - name: Cleanup
      ansible.builtin.include_tasks: tasks/provision-cleanup.yml
