---
- name: SignalQube Profile
  hosts: localhost
  become: true
  tasks:
    - name: Setup
      ansible.builtin.include_tasks: tasks/provision-setup.yml

    - name: Provision Signal App
      ansible.builtin.include_tasks: tasks/provision-signal.yml

    - name: Cleanup
      ansible.builtin.include_tasks: tasks/provision-cleanup.yml
