---
- name: Configure NodeJS Environment
  hosts: localhost
  become: false
  vars:
    nvm_ver: "https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1"
    nvm_dir: "{{ ansible_env.HOME }}/.nvm"
  tasks:
    - name: Create default NVM_DIR
      file:
        path: "{{ nvm_dir }}"
        state: directory

    - name: Install Node Version Manager (NVM)
      shell: >
        curl -o- {{ nvm_ver }}/install.sh | NVM_DIR={{ nvm_dir }} bash
      args:
        creates: "{{ nvm_dir }}/nvm.sh"

    - name: Install node.js versions
      shell: >
        source {{ nvm_dir }}/nvm.sh && nvm install {{ item }}
      args:
        creates: "{{ nvm_dir }}/versions/node/v{{ item }}"
        chdir: "{{ ansible_env.HOME }}"
        executable: /bin/bash
      loop:
        - 16.17.0  # LTS
