---
- name: Provision Chrome OS Workstation
  hosts: localhost
  become: true
  vars_prompt:
    - name: var_users
      prompt: Docker users
      default: "{{ lookup('env', 'USER') }}"
      private: false
  tasks:
    - name: Create temporary directory
      tempfile:
        state: directory
        suffix: ansible
      register: tmpdir

    - name: Install general system tools
      apt:
        name:
          - python3
          - python3-pip
          - python3-apt
          - ansible
          - curl
          - tmux
          - gcc
          - groff
          - gawk
          - software-properties-common
        state: latest
        update_cache: true

    - name: Install system security tools
      apt:
        name:
          - ca-certificates
          - pass
          - gnupg2
          - paperkey
          - opensc
          - scdaemon
          - pcscd
          - pcsc-tools
          - secure-delete

    - name: Install user applications
      apt:
        name:
          - mutt
        state: latest

    - name: Install user python packages
      become: false
      pip:
        name: pipenv
        extra_args: --user

    - name: Add Docker GPG apt key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: >
          deb https://download.docker.com/linux/debian
          "{{ ansible_distribution_release }}"
          stable
        state: present

    - name: Install docker-ce
      apt:
        name: docker-ce
        state: latest
        update_cache: true

    - name: Create Docker group
      group:
        name: docker
        state: present

    - name: Add user(s) to Docker group
      user:
        name: "{{ item }}"
        groups: docker
        append: true
      with_items: "{{ var_users }}"

    - name: Get Docker credential helper
      get_url:
        url: https://github.com/docker/docker-credential-helpers/releases/download/v0.6.4/docker-credential-pass-v0.6.4-amd64.tar.gz
        dest: "{{ tmpdir.path }}/docker-credential-pass.tar.gz"
        checksum: "sha256:23ee4682adc93058d94b27f15a31bafd13a89c2de1c3092a04f30b43cf7c323d"

    - name: Unpack Docker credential helper to ~/.local/bin
      unarchive:
        remote_src: true
        src: "{{ tmpdir.path }}/docker-credential-pass.tar.gz"
        dest: "{{ lookup('env', 'HOME') }}/.local/bin/"
        creates: "{{ lookup('env', 'HOME') }}/.local/bin/docker-credential-pass"

    - name: Configure Docker to use pass credential helper
      shell: |
        sed -i '0,/{/s/{/{\n\t"credsStore": "pass",/' .docker/config.json
      args:
        chdir: "{{ lookup('env', 'HOME') }}"
