---
- name: Provision Chrome OS Workstation
  hosts: localhost
  become: true
  vars_prompt:
    - name: var_users
      prompt: Docker users
      default: "{{ lookup('env', 'USER') }}"
      private: false
  tasks:

    - name: Install general system tools
      apt:
        name:
          - python3
          - python3-pip
          - python3-apt
          - ansible
          - curl
          - tmux
          - gcc
          - groff
          - gawk
          - software-properties-common
        state: latest
        update_cache: true

    - name: Install system security tools
      apt:
        name:
          - ca-certificates
          - pass
          - gnupg2
          - paperkey
          - opensc
          - scdaemon
          - pcscd
          - pcsc-tools
          - secure-delete

    - name: Install user applications
      apt:
        name:
          - mutt
        state: latest

    - name: Install user python packages
      become: false
      pip:
        name: pipenv
        extra_args: --user

    - name: Add Docker GPG apt key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: >
          deb https://download.docker.com/linux/debian
          "{{ ansible_distribution_release }}"
          stable
        state: present

    - name: Install docker-ce
      apt:
        name: docker-ce
        state: latest
        update_cache: true

    - name: Create Docker group
      group:
        name: docker
        state: present

    - name: Add user(s) to Docker group
      user:
        name: "{{ item }}"
        groups: docker
        append: true
      with_items: "{{ var_users }}"
