---
- name: (RHEL) Provision Linux NXT Development Environment
  hosts: localhost
  become: true
  tasks:
    - name: Create legonxt group
      ansible.builtin.group:
        name: legonxt
        state: present

    - name: Add user(s) to legonxt group
      ansible.builtin.user:
        name: "{{ item }}"
        groups: legonxt
        append: true
      with_items: "{{ lookup('env', 'USER') }}"

    - name: (RHEL) Add NXT toolchain
      ansible.builtin.package:
        name:
          - nbc
        state: present

    - name: Configure custom rules under /etc/udev/rules.d
      ansible.builtin.blockinfile:
        path: /etc/udev/rules.d/45-legonxt.rules
        create: true
        mode: "0644"
        block: |
          # LEGO NXT brick
          SUBSYSTEM=="usb", ATTRS{idVendor}=="0694", ATTRS{idProduct}=="0002", \
            SYMLINK+="legonxt-%k", GROUP="legonxt", MODE="0666"

          # Lego NXT brick (Atmel SAM-BA mode)
          SUBSYSTEM=="usb", ATTRS{idVendor}=="03eb", ATTRS{idProduct}=="6124", \
            SYMLINK+="legonxt-%k", GROUP="legonxt", MODE="0666"

    - name: Reload udev rules # noqa: no-changed-when
      ansible.builtin.shell: |
        udevadm control --reload
        udevadm trigger
      args:
        executable: /bin/bash
