---
- name: Configure NodeJS Environment
  hosts: localhost
  become: false
  vars:
    nvm_uri: "https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7"
    nvm_dir: "{{ ansible_env.HOME }}/.nvm"
  tasks:
    - name: Create default NVM_DIR
      ansible.builtin.file:
        path: "{{ nvm_dir }}"
        state: directory
        mode: "0700"

    - name: Download Node version Manager (NVM) Installer
      ansible.builtin.get_url:
        url: "{{ nvm_uri }}/install.sh"
        dest: "{{ nvm_dir }}"
        mode: "0700"
        checksum: "sha256:8e45fa547f428e9196a5613efad3bfa4d4608b74ca870f930090598f5af5f643"

    - name: Install Node Version Manager (NVM)
      ansible.builtin.shell: >
        NVM_DIR={{ nvm_dir }} ./install.sh
      args:
        creates: "{{ nvm_dir }}/nvm.sh"
        chdir: "{{ nvm_dir }}"
        executable: /bin/sh

    - name: Install node.js versions
      ansible.builtin.shell: >
        source {{ nvm_dir }}/nvm.sh && nvm install {{ item }}
      args:
        creates: "{{ nvm_dir }}/versions/node/v{{ item }}"
        chdir: "{{ ansible_env.HOME }}"
        executable: /bin/sh
