---
- name: Configure Rust Environment
  hosts: localhost
  become: false
  tasks:
    - name: Create temporary directory
      ansible.builtin.tempfile:
        state: directory
        suffix: ansible
      register: tmpdir
      check_mode: false

    - name: Download rustup Installer
      ansible.builtin.get_url:
        url:  "https://sh.rustup.rs"
        dest: "{{ tmpdir.path }}"
        mode: 0700
        checksum: "sha256:173f4881e2de99ba9ad1acb59e65be01b2a44979d83b6ec648d0d22f8654cbce"

    - name: Install Rust Installer
      ansible.builtin.shell: >
        ./rustup-init.sh -y --no-modify-path
      args:
        creates: "{{ ansible_env.HOME }}/.rustup/settings.toml"
        chdir: "{{ tmpdir.path }}"
        executable: /bin/sh
