- name: Configure Python Environment
  hosts: localhost
  vars:
    pyenv_version: "v2.4.17"
    python_version: "3.12.0"
  become: false
  environment:
    TMPDIR: "{{ alt_tmpdir | default('/tmp') }}"
  tasks:
    - name: Configure pyenv
      ansible.builtin.git:
        repo: https://github.com/pyenv/pyenv.git
        dest: "{{ ansible_env.HOME }}/.pyenv"
        version: "{{ pyenv_version }}"

    - name: Install new default Python version using pyenv
      ansible.builtin.shell: |
        export PYENV_ROOT="$HOME/.pyenv"
        export PATH="$PYENV_ROOT/bin:$PATH"
        eval "$(pyenv init --path)"
        pyenv install {{ python_version }}
      args:
        executable: /bin/bash
        creates: "{{ ansible_env.HOME }}/.pyenv/versions/{{ python_version }}"

    - name: Ensure core pip packages are installed
      ansible.builtin.pip:
        name: "{{ item }}"
        state: present
        extra_args: --user
      with_items:
        - pip
        - ansible
        - ansible-lint
        - poetry
