---
- name: Configure Anki
  hosts: localhost
  become: false
  environment:
    TMPDIR: "{{ alt_tmpdir | default('/tmp') }}"
  vars:
    anki: "anki-25.02-linux-qt6.tar.zst"
    anki_version: "25.02"
    anki_sha256: "f60f64b44304e0ff30418bfc8bc4f32174e1a6c4e2e10b89353746740f98a8d0"
  tasks:
    - name: Create temporary directory
      ansible.builtin.tempfile:
        state: directory
        suffix: ansible
      register: tmpdir
      check_mode: false

    - name: Download Anki bundle
      ansible.builtin.get_url:
        url: "https://github.com/ankitects/anki/releases/download/{{ anki_version }}/{{ anki }}"
        dest: "{{ tmpdir.path }}"
        mode: "0700"
        checksum: "sha256:{{ anki_sha256 }}"

    - name: Extract Anki bundle
      ansible.builtin.unarchive:
        src: "{{ tmpdir.path }}/{{ anki }}"
        dest: "{{ tmpdir.path }}"
        extra_opts: ["--strip-components=1"]

    - name: Install Anki
      ansible.builtin.shell: >
        PREFIX="{{ ansible_env.HOME }}/.local" ./install.sh
      args:
        creates: "{{ ansible_env.HOME }}/.local/bin/anki"
        chdir: "{{ tmpdir.path }}"
        executable: /bin/sh
