---
- name: Fetch and install Shelltools
  hosts: localhost
  vars:
    shfmt_version: "v3.11.0"
    shfmt_sha256: "1904ec6bac715c1d05cd7f6612eec8f67a625c3749cb327e5bfb4127d09035ff"
    shfmt_url: "https://github.com/mvdan/sh/releases/download/{{ shfmt_version }}/shfmt_{{ shfmt_version }}_linux_amd64"
    shellcheck_version: "v0.10.0"
    shellcheck_sha256: "6c881ab0698e4e6ea235245f22832860544f17ba386442fe7e9d629f8cbedf87"
  tasks:
    - name: Ensure ~/.local/bin directory exists
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.local/bin"
        state: directory
        mode: '0755'

    - name: Download shellcheck package
      ansible.builtin.get_url:
        url: "https://github.com/koalaman/shellcheck/releases/download/{{ shellcheck_version }}/shellcheck-{{ shellcheck_version }}.linux.x86_64.tar.xz"
        dest: /tmp/shellcheck.linux.x86_64.tar.xz
        mode: "0700"
        checksum: "sha256:{{ shellcheck_sha256 }}"

    - name: Extract shellcheck package
      ansible.builtin.unarchive:
        src: /tmp/shellcheck.linux.x86_64.tar.xz
        dest: "{{ ansible_env.HOME }}/.local"
        remote_src: true

    - name: Create a symlink to shellcheck binary
      ansible.builtin.file:
        src: "{{ ansible_env.HOME }}/.local/shellcheck-{{ shellcheck_version }}/shellcheck"
        dest: "{{ ansible_env.HOME }}/.local/bin/shellcheck"
        state: link
