---
- name: Configure Rust Environment
  hosts: localhost
  become: false
  tasks:
    - name: Create temporary directory
      ansible.builtin.tempfile:
        state: directory
        suffix: ansible
      register: tmpdir
      check_mode: false

    - name: Download rustup Installer Package
      ansible.builtin.get_url:
        url: "https://github.com/rust-lang/rustup/archive/refs/tags/1.26.0.tar.gz"
        dest: "{{ tmpdir.path }}"
        checksum: "sha256:6f20ff98f2f1dbde6886f8d133fe0d7aed24bc76c670ea1fca18eb33baadd808"

    - name: Unpack rustup Installer
      unarchive:
        src: "{{ tmpdir.path }}/rustup-1.26.0.tar.gz"
        dest: "{{ tmpdir.path }}"

    - name: Install Rust Installer
      ansible.builtin.shell: >
        ./rustup-1.26.0/rustup-init.sh -y --no-modify-path
      args:
        creates: "{{ ansible_env.HOME }}/.rustup/settings.toml"
        chdir: "{{ tmpdir.path }}"
        executable: /bin/sh
