---
- name: Configure Kerberos
  hosts: localhost
  become: false
  vars:
    kerberos: "HPCMP_RELEASE_20210920_client-3.10.0-1127.el7.x86_64-Linux-64.tar.gz"
    openssh: "user-openssh-8.7p1a-x86_64-unknown-linux-gnu.tgz"
    kerberos_sha256: "3e27093790c97a4be50479e9a465c0953e669dd1afd537ef425e537bf9f9faf4"
    openssh_sha256: "314e4d7043ca456099abc0006d17a963c0f186d3cc657c31d9a6c5aed2095c64"
  tasks:
    - name: Get checksum of Kerberos installer
      ansible.builtin.stat:
        path: "{{ ansible_env.HOME }}/Downloads/{{ kerberos }}"
        checksum_algorithm: sha256
      register: kerberos_stat

    - name: Get checksum of OpenSSH installer
      ansible.builtin.stat:
        path: "{{ ansible_env.HOME }}/Downloads/{{ openssh }}"
        checksum_algorithm: sha256
      register: openssh_stat

    - name: Verify checksum of Kerberos installer
      ansible.builtin.fail:
        msg: "Checksum of Kerberos installer does not match"
      when: kerberos_stat.stat.checksum != kerberos_sha256

    - name: Verify checksum of OpenSSH installer
      ansible.builtin.fail:
        msg: "Checksum of OpenSSH installer does not match"
      when: openssh_stat.stat.checksum != openssh_sha256

    - name: Unarchive Kerberos installer to ~/.local
      ansible.builtin.unarchive:
        src: "{{ ansible_env.HOME }}/Downloads/{{ kerberos }}"
        dest: "{{ ansible_env.HOME }}/.local"
        remote_src: true
        creates: "{{ ansible_env.HOME }}/.local/krb5"

    - name: Unarchive OpenSSH installer to ~/.local
      ansible.builtin.unarchive:
        src: "{{ ansible_env.HOME }}/Downloads/{{ openssh }}"
        dest: "{{ ansible_env.HOME }}/.local"
        remote_src: true
        creates: "{{ ansible_env.HOME }}/.local/ossh"
