---
- name: Configure Kerberos
  hosts: localhost
  become: false
  vars:
    kerberos: "kerberos-client.x86_64.rpm"
    kerberos_sha256: "10e2b2a0c22ab20f7f672e00d535cc7221fbfa12cc3811a9ec7bd449d7c72a0d"
  tasks:
    - name: Get checksum of Kerberos installer
      ansible.builtin.stat:
        path: "{{ ansible_env.HOME }}/Downloads/{{ kerberos }}"
        checksum_algorithm: sha256
      register: kerberos_stat

    - name: Verify checksum of Kerberos installer
      ansible.builtin.fail:
        msg: "Checksum of Kerberos installer does not match"
      when: kerberos_stat.stat.checksum != kerberos_sha256

    - name: Create temporary directory
      ansible.builtin.tempfile:
        state: directory
        suffix: ansible
      register: tmpdir
      check_mode: false

    - name: Unpack Kerberos installer to ~/.local
      ansible.builtin.shell: |
        set -o pipefail
        rpm2cpio "{{ kerberos_stat.stat.path }}" | cpio -idmv -D "{{ tmpdir.path }}"
        tar -C "{{ tmpdir.path }}" -cf - . | tar --strip-components=3 -C "{{ ansible_env.HOME }}/.local"  -xf -
      args:
        executable: /bin/bash
        creates: "${{ ansible_env.HOME }}/.local/krb5"
