---
- name: SignalQube Profile
  hosts: localhost
  become: true
  tasks:
    - include_tasks: tasks/provision-setup.yml

    - include_tasks: tasks/provision-signal.yml

    - include_tasks: tasks/provision-cleanup.yml
