---
- name: Oxidize
  hosts: localhost
  become: false
  environment:
    TMPDIR: "{{ alt_tmpdir | default('/tmp') }}"
  vars:
    tools:
      - name: exa # ls
        version: 0.10.1
        exe: exa

      - name: fd-find # find
        version: 10.2.0
        exe: fd

      - name: ripgrep # grep
        version: 14.1.1
        exe: rg

      - name: bat # cat
        version: 0.24.0
        exe: bat

      - name: grex # regexgen
        version: 1.4.5
        exe: grex

      - name: tokei # cloc
        version: 12.1.2
        exe: tokei

      - name: du-dust # du
        version: 1.0.0
        exe: dust

      - name: eva # bc
        version: 0.3.1
        exe: eva
  tasks:
    - name: Check existing tool installation
      ansible.builtin.command: "{{ item.exe }} --version"
      register: version_output
      ignore_errors: true
      loop: "{{ tools }}"
      changed_when: false

    - name: Fetch versions of installed tools
      ansible.builtin.set_fact:
        updated_tools: "{{ updated_tools | default([]) + [item.0 | combine({'installed_version': installed})] }}"
      vars:
        installed: "{{ item.1.stdout | regex_search('[0-9]+\\.[0-9]+\\.[0-9]+') }}"
      with_together:
        - "{{ tools }}"
        - "{{ version_output.results }}"
      loop_control:
        label: "{{ item.0.name }}"

    - name: Install tools, as required
      ansible.builtin.shell: >
        cargo install {{ item.name }} --version {{ item.version }}
      args:
        executable: /bin/bash
      when: item.version != item.installed_version
      changed_when: item.version != item.installed_version
      loop: "{{ updated_tools }}"
