---
- name: Workstation Profile
  hosts: localhost
  become: true
  tasks:
    - name: Add common system tools
      package:
        name:
          - git
          - tmux
          - gawk
          - python3
          - python3-pip
          - ansible
        state: present

    - name: Add common productivity tools
      package:
        name:
          - vim
          - neovim
          - groff
          - aspell
          - aspell-en
        state: present

    - include_tasks: provision-security.yml

    - include_tasks: provision-certs.yml

    - include_tasks: provision-chrome.yml

    - include_tasks: provision-docker.yml

    - include_tasks: provision-netclient.yml

    - when: ansible_os_family == 'Debian'
      block:
        - name: (Debian) Add system tools
          package:
            name:
              - python3-apt
            state: present

        - name: (Debian) Add development tools
          package:
            name:
              - build-essential
            state: present

        - name: (Debian) Add office productivity tools
          package:
            name:
              - mutt
            state: present

    - when: ansible_os_family == 'RedHat'
      block:
        - name: (RHEL) Add system tools
          package:
            name:
              - python3-dnf
            state: present

        - name: (RHEL) Add development tools
          package:
            name:
              - '@Development tools'
            state: present

        - name: (RHEL) Add office productivity tools
          package:
            name:
              - libreoffice
            state: present

    - include: provision-cleanup.yml
