---
- name: (Debian) Upgrade all packages to their latest versions
  when: ansible_os_family == 'Debian'
  apt:
    name: "*"
    state: latest
    autoclean: true
    autoremove: true

- when: ansible_os_family == 'RedHat'
  block:
    - name: (RHEL) Upgrade all packages to their latest versions
      dnf:
        name: "*"
        state: latest

    - name: (RHEL) Autoremove old packages
      dnf:
        autoremove: true



