---
- name: Provision Google Chrome on the local host
  hosts: localhost
  become: true
  tasks:
    - name: Add third-party Fedora repositories
      dnf:
        name: fedora-workstation-repositories
        state: present

    - name: Install Google Chrome stable (third-party)
      dnf:
        name: google-chrome-stable
        enablerepo: google-chrome
        state: present
