---
- when: ansible_os_family == 'RedHat'
  block:
    - name: (RHEL) Add third-party Fedora repositories
      dnf:
        name: fedora-workstation-repositories
        state: present

    - name: (RHEL) Add Google Chrome stable (third-party)
      dnf:
        name: google-chrome-stable
        enablerepo: google-chrome
        state: present
