---
- name: Provision root certs on the local host
  hosts: localhost
  tasks:
    - name: Check packages
      package_facts:
        manager: auto

    - name: Verify package dependencies
      loop:
        - nss-tools
        - pcsc-tools
        - opensc
      fail:
        msg: "Missing '{{ item }}' system package"
      when: item not in ansible_facts.packages

    - name: Create temporary directory
      tempfile:
        state: directory
        suffix: tmpdir
      register: tmpdir

    - name: Obtain Root CA certificate bundle
      get_url:
        url: "https://dl.dod.cyber.mil/wp-content/uploads/pki-pke/zip/certificates_pkcs7_DoD.zip"
        dest: "{{ tmpdir.path }}/certificates_pkcs7_DoD.zip"

    - name: Unpack Root CA certificate bundle
      unarchive:
        src: "{{ tmpdir.path }}/certificates_pkcs7_DoD.zip"
        dest: "{{ tmpdir.path }}/"

      # certutil -d sql:$HOME/.pki/nssdb/ -L
      # openssl pkcs7 -print_certs -in *pem.p7b -out certs.crt
      # certutil -d sql:$HOME/.pki/nssdb -A -t TC -n certs.crt -i certs.crt
    - name: Import p7b files into the trust store
      shell: |
        mkdir -p $HOME/.pki/nssdb
        for n in *.p7b; do certutil -d sql:$HOME/.pki/nssdb -A -t TC -n $n -i $n; done
      args:
        chdir: "{{ tmpdir.path }}/Certificates_PKCS7_v5.9_DoD"
        executable: /bin/bash

    - name: Configure PKCS11 module
      blockinfile:
        block: |
          module: /usr/lib64/pkcs11/opensc-pkcs11.so
        path: "{{ ansible_env.HOME }}/.config/pkcs11/pkcs11.conf"
        marker: "# {mark} ANSIBLE MANAGED BLOCK"
        create: yes
