---
- name: Provision Fedora Workstation VM
  hosts: localhost
  become: true
  tasks:
    - name: Provision Google Chrome on the local host
      include_tasks: provision-chrome.yml

    - name: Add essential productivity tools
      dnf:
        name:
          - git
          - curl-minimal
          - tmux
          - vim
          - neovim
          - libreoffice
          - aspell
          - aspell-en
        state: present

    - name: Add container management tools
      dnf:
        name:
          - buildah
          - podman
          - skopeo
        state: present

    - name: Add essential development tools
      dnf:
        name:
          - '@Development tools'
          - cmake
        state: present

    - name: Add dependencies for graphical applications
      dnf:
        name:
          - mesa-libGLU
        state: present

    - name: Upgrade all packages to their latest versions
      dnf:
        name: "*"
        state: latest
