---
- name: (Debian) Upgrade all packages to their latest versions
  when: ansible_os_family == 'Debian'
  ansible.builtin.apt:
    name: "*"
    state: latest
    only_upgrade: true
    autoclean: true
    autoremove: true

- name: (RHEL) Upgrade all packages and cleanup
  when: ansible_os_family == 'RedHat'
  block:
    - name: (RHEL) Upgrade all packages to their latest versions
      ansible.builtin.dnf:
        name: "*"
        state: latest
        update_only: true

    - name: (RHEL) Autoremove old packages
      ansible.builtin.dnf:
        autoremove: true
