---
- name: (RHEL) Install DoD Root Certificate Authorities
  when: ansible_os_family == 'RedHat'
  block:
    - name: (RHEL) Create temporary directory
      ansible.builtin.tempfile:
        state: directory
        suffix: ansible
      register: tmpdir
      check_mode: false

    - name: (RHEL) Obtain Root CA certificate bundle
      ansible.builtin.get_url:
        url: "https://dl.dod.cyber.mil/wp-content/uploads/pki-pke/zip/certificates_pkcs7_DoD.zip"
        dest: "{{ tmpdir.path }}/certificates_pkcs7_DoD.zip"
        mode: "0644"
        checksum: sha256:557dd02c22ba0fd28ac8390958565f51bdd5aef53fc7320342c6881a9a5103c8
      check_mode: false

    - name: (RHEL) Unpack Root CA certificate bundle
      ansible.builtin.unarchive:
        src: "{{ tmpdir.path }}/certificates_pkcs7_DoD.zip"
        dest: "{{ tmpdir.path }}/"
        remote_src: true
      check_mode: false

    - name: (RHEL) Add smart card support (PC/SC, OpenSC, NSS)
      ansible.builtin.package:
        name:
          - nss-tools
          - pcsc-tools
          - opensc
          - openssl
        state: present

    - name: (RHEL) Add Root CA certificates
      ansible.builtin.shell: |
        openssl pkcs7 -in Certificates_PKCS7_v5.9_DoD.pem.p7b -print_certs -out DoD_CAs_v5.9.pem
        cp DoD_CAs_v5.9.pem /etc/pki/ca-trust/source/anchors/
        update-ca-trust
      args:
        creates: /etc/pki/ca-trust/source/anchors/DoD_CAs_v5.9.pem
        chdir: "{{ tmpdir.path }}/Certificates_PKCS7_v5.9_DoD"
