---
- name: (Debian) Add Signal desktop client
  when: ansible_os_family == 'Debian'
  # NOTE: These instructions only work for 64 bit Debian-based
  # # Linux distributions such as Ubuntu, Mint etc.
  #
  # # 1. Install our official public software signing key
  # wget -O- https://updates.signal.org/desktop/apt/keys.asc | gpg --dearmor > signal-desktop-keyring.gpg
  # cat signal-desktop-keyring.gpg | sudo tee -a /usr/share/keyrings/signal-desktop-keyring.gpg > /dev/null
  #
  # # 2. Add our repository to your list of repositories
  # echo 'deb [arch=amd64 signed-by=/usr/share/keyrings/signal-desktop-keyring.gpg] https://updates.signal.org/desktop/apt xenial main' |\
  #   sudo tee -a /etc/apt/sources.list.d/signal-xenial.list
  #
  # # 3. Update your package database and install signal
  # sudo apt update && sudo apt install signal-desktop
  block:
    - name: (Debian) Add Signal GPG apt key
      ansible.builtin.apt_key:
        url: https://updates.signal.org/desktop/apt/keys.asc
        keyring: /usr/share/keyrings/signal-desktop-keyring.gpg
        state: present

    - name: (Debian) Add Signal repository
      ansible.builtin.apt_repository:
        repo: >
          deb [arch=amd64 signed-by=/usr/share/keyrings/signal-desktop-keyring.gpg]
          https://updates.signal.org/desktop/apt
          xenial
          main
        state: present

    - name: (Debian) Add Signal desktop client
      ansible.builtin.apt:
        name: signal-desktop
        state: latest
        only_upgrade: true
        update_cache: true
