---
- name: (Debian) Add Docker for container management
  when: ansible_os_family == 'Debian'
  block:
    - name: (Debian) Identify Docker group users
      ansible.builtin.pause:
        prompt: Add user(s) to Docker group (e.g., "{{ lookup('env', 'USER') }}")
        echo: true
      register: var_users

    - name: (Debian) Add Docker repository dependencies
      ansible.builtin.apt:
        name:
          - ca-certificates
          - gnupg2
          - lsb-release
        update_cache: true

    - name: (Debian) Add Docker GPG apt key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: (Debian) Add Docker repository
      ansible.builtin.apt_repository:
        repo: >
          deb https://download.docker.com/linux/debian
          "{{ ansible_distribution_release }}"
          stable
        state: present

    - name: (Debian) Add docker-ce"
      ansible.builtin.apt:
        name: docker-ce
        state: latest
        only_upgrade: true
        update_cache: true

    - name: Add Docker group
      ansible.builtin.group:
        name: docker
        state: present

    - name: Add user(s) to Docker group
      ansible.builtin.user:
        name: "{{ item }}"
        groups: docker
        append: true
      with_items: "{{ var_users.user_input }}"

- name: (RHEL) Add container management tools
  when: ansible_os_family == 'RedHat'
  ansible.builtin.package:
    name:
      - buildah
      - podman
      - skopeo
    state: present
