---
- name: (RHEL) Configure python builder environment
  when: ansible_os_family == 'RedHat'
  block:
  - name: (RHEL) Add development tools
    ansible.builtin.package:
      name:
        - '@Development tools'
      state: present

    - name: (RHEL) Add python build dependencies
      ansible.builtin.package:
        name:
          - zlib-devel
          - bzip2
          - bzip2-devel
          - readline-devel
          - sqlite
          - sqlite-devel
          - openssl-devel
          - tk-devel
          - libffi-devel
          - xz-devel
        state: present

- name: (Debian) Configure python builder environment
  when: ansible_os_family == 'Debian'
  block:
    - name: (Debian) Add development tools
      ansible.builtin.package:
        name:
          - build-essential
        state: present

    - name: (Debian) Add python build dependencies
      ansible.builtin.package:
        name:
          - libssl-dev
          - zlib1g-dev
          - libbz2-dev
          - libreadline-dev
          - libsqlite3-dev
          - llvm
          - libncursesw5-dev
          - xz-utils
          - tk-dev
          - libxml2-dev
          - libxmlsec1-dev
          - libffi-dev
          - liblzma-dev
        state: present
