# Ansible task to install Visual Studio Code
---
- name: (RHEL) Add Visual Studio Code RPM Repository
  when: ansible_os_family == 'RedHat'
  block:
    - name: (RHEL) Import Microsoft Signing Key
      ansible.builtin.rpm_key:
        key: https://packages.microsoft.com/keys/microsoft.asc
        state: present
    - name: (RHEL) Add Repository
      ansible.builtin.yum_repository:
        name: Visual Studio Code
        description: Visual Studio Code
        baseurl: https://packages.microsoft.com/yumrepos/vscode
        gpgcheck: true
        gpgkey: https://packages.microsoft.com/keys/microsoft.asc
        enabled: true
        state: present

- name: (RHEL) Install Visual Studio Code
  when: ansible_os_family == 'RedHat'
  ansible.builtin.package:
    name: code
    state: present
