name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, feature-* ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # https://github.com/marketplace/actions/shellcheck
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master
      env:
        # (-e SC1071) ShellCheck only supports sh/bash/dash/ksh scripts
        SHELLCHECK_OPTS: -e SC1071
      with:
        ignore: other
  test:
    name: Test
    runs-on: ubuntu-latest
#   runs-on: ${{ matrix.os }}
#   strategy:
#     matrix:
#       os: [ubuntu-latest macos-latest]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run Test
      run: ./test.sh
      shell: bash
