name: CI

on:
  push:
    branches: [ master, feature-* ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, fedora-latest]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run Test
      run: ./test.sh
      shell: bash
