name: ShellCheck

on:
  push:
    branches: [ master, feature-* ]
  pull_request:
    branches: [ master ]

jobs:
  # https://github.com/marketplace/actions/shellcheck
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master
      env:
        # (-e SC1071) ShellCheck only supports sh/bash/dash/ksh scripts
        SHELLCHECK_OPTS: -e SC1071
      with:
        ignore_paths: other
