name: Vint

on:
  push:
    branches: [ master, feature-* ]
  pull_request:
    branches: [ master ]

jobs:
  vint:
    name: Vint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run Vint
      uses: reviewdog/action-vint@v1.0.1
      with:
        github_token: ${{ secrets.github_token }}
        reporter: github-pr-review
